added plugin to upload kpm to server after emails are sent
securestate/king-phisher-plugins pull request #9
Opened 2016-12-27 20:42 UTC by shad0wman

@wolfthefallen @zeroSteiner 

So this plugin was a request from Spencer to upload a kpm file after emails are sent (signal = 'send-finished' . What this plugin does is:
1. packs up the KPM (had to recycle some code from the client in order to specify a directory) and saves it as {{ username }}_{{ campaign_name }}_{{ current-time/date }}.kpm in a local directory which can be specified by the user in preferences
2. uploads the KPM to the connected server via sftp (standalone instance) to a folder the user may specify or defaults to /usr/share.

Limitations:
- Users must have keyed authentication enabled (no password option) to upload file
- Users must have write access to the folder they're trying to upload to

How-to-test:
1. Install plugin
2. Send test email
3. watch debugger and check for new files.

2016-12-27 21:28 UTC, wolfthefallen requested changes

2016-12-27 21:28 UTC, wolfthefallen commented on client/upload-kpm.py
> +		port = int(self.application.config['server'].split(':', 2)[1])
No need to create a new ssh connection, King Phisher should already have a connection to the server. `self.application._ssh_forwarder`
```
ssh_connection = self.application._ssh_forwarder
if not ssh_connection:
  return "No ssh connection"

sftp = paramiko.SFTPClient.from_transport(ssh_connection)
```

This prevents the need of redefining the username/password/ssh_key and no need to create another ssh instance to the server.

2016-12-27 21:28 UTC, wolfthefallen commented on client/upload-kpm.py
> +		self.upload_kpm(local_kpm, filename, username)
you will not need to pass username

2016-12-27 21:28 UTC, wolfthefallen commented on client/upload-kpm.py
> +		local_kpm = self.config['local_directory'] + '/' + filename
use 'os.path.join(path, path, filename)' . This provides better support for both Linux and Windows user clients.

2016-12-27 21:28 UTC, wolfthefallen commented on client/upload-kpm.py
> +		target_kpm = self.config['remote_directory'] + '/' + filename
for windows support make sure you `import posixpath` then use its `path.join` method.

2016-12-28 15:20 UTC, wolfthefallen commented on client/upload-kpm.py
> +		target_kpm = os.path.join(remote_directory, filename)
this should use `posixpath.os.path.join` as upload should always be a Linux path. If this runs on a windows box, currently the pathing would not be compatible.

2016-12-28 20:08 UTC, merged

2016-12-28 20:09 UTC, zeroSteiner commented
I landed this after making some style changes and fixing a bug in how the configuration was processed. The error existed in the fact that the plugins config is not the same as the applications config. I also renamed this to be a bit more consistent with the other plugins.

Thanks for the submission @shad0wman!